export const regions = [
  {
    city: "Seoul",
    districts: [
      "Gangnam-gu",
      "Gangdong-gu",
      "Gangbuk-gu",
      "Gangseo-gu",
      "Gwanak-gu",
      "Gwangjin-gu",
      "Guro-gu",
      "Geumcheon-gu",
      "Nowon-gu",
      "Dobong-gu",
      "Dongdaemun-gu",
      "Dongjak-gu",
      "Mapo-gu",
      "Seodaemun-gu",
      "Seocho-gu",
      "Seongdong-gu",
      "Seongbuk-gu",
      "Songpa-gu",
      "Yangcheon-gu",
      "Yeongdeungpo-gu",
      "Yongsan-gu",
      "Eunpyeong-gu",
      "Jongno-gu",
      "Jung-gu",
      "Jungnang-gu",
    ],
  },
  {
    city: "Busan",
    districts: [
      "Haeundae-gu",
      "Suyeong-gu",
      "Nam-gu",
      "Dong-gu",
      "Seo-gu",
      "Busanjin-gu",
      "Buk-gu",
      "Sasang-gu",
      "Saha-gu",
      "Gangseo-gu",
      "Yeonje-gu",
      "Yeongdo-gu",
      "Geumjeong-gu",
      "Gijang-gun",
    ],
  },
];
