export const regions = [
  {
    province: "Seoul",
    type: "metropolitan",
    districts: [
      "Gangnam-gu",
      "Gangdong-gu",
      "Gangbuk-gu",
      "Gangseo-gu",
      "Gwanak-gu",
      "Gwangjin-gu",
      "Guro-gu",
      "Geumcheon-gu",
      "Nowon-gu",
      "Dobong-gu",
      "Dongdaemun-gu",
      "Dongjak-gu",
      "Mapo-gu",
      "Seodaemun-gu",
      "Seocho-gu",
      "Seongdong-gu",
      "Seongbuk-gu",
      "Songpa-gu",
      "Yangcheon-gu",
      "Yeongdeungpo-gu",
      "Yongsan-gu",
      "Eunpyeong-gu",
      "Jongno-gu",
      "Jung-gu",
      "Jungnang-gu",
    ],
  },
  {
    province: "Busan",
    type: "metropolitan",
    districts: [
      "Gangseo-gu",
      "Geumjeong-gu",
      "Gijang-gun",
      "Nam-gu",
      "Dong-gu",
      "Dongnae-gu",
      "Busanjin-gu",
      "Buk-gu",
      "Sasang-gu",
      "Saha-gu",
      "Seo-gu",
      "Suyeong-gu",
      "Yeonje-gu",
      "Yeongdo-gu",
      "Jung-gu",
      "Haeundae-gu",
    ],
  },
  {
    province: "Daegu",
    type: "metropolitan",
    districts: [
      "Dalseo-gu",
      "Dalseong-gun",
      "Dong-gu",
      "Nam-gu",
      "Buk-gu",
      "Seo-gu",
      "Suseong-gu",
      "Jung-gu",
    ],
  },
  {
    province: "Incheon",
    type: "metropolitan",
    districts: [
      "Ganghwa-gun",
      "Gyeyang-gu",
      "Namdong-gu",
      "Dong-gu",
      "Bupyeong-gu",
      "Seo-gu",
      "Yeonsu-gu",
      "Michuhol-gu",
      "Jung-gu",
    ],
  },
  {
    province: "Gwangju",
    type: "metropolitan",
    districts: ["Buk-gu", "Dong-gu", "Gwangsan-gu", "Nam-gu", "Seo-gu"],
  },
  {
    province: "Daejeon",
    type: "metropolitan",
    districts: ["Daedeok-gu", "Dong-gu", "Seo-gu", "Yuseong-gu", "Jung-gu"],
  },
  {
    province: "Ulsan",
    type: "metropolitan",
    districts: ["Nam-gu", "Dong-gu", "Buk-gu", "Ulju-gun", "Jung-gu"],
  },
  {
    province: "Gyeonggi",
    type: "province",
    districts: [
      {
        city: "Suwon",
        areas: ["Jangan-gu", "Gwonseon-gu", "Paldal-gu", "Yeongtong-gu"],
      },
      {
        city: "Seongnam",
        areas: ["Sujeong-gu", "Jungwon-gu", "Bundang-gu"],
      },
      {
        city: "Yongin",
        areas: ["Cheoin-gu", "Giheung-gu", "Suji-gu"],
      },
      {
        city: "Anyang",
        areas: ["Manan-gu", "Dongan-gu"],
      },
      {
        city: "Bucheon",
        areas: ["Wonmi-gu", "Ojeong-gu", "Sosa-gu"],
      },
      {
        city: "Goyang",
        areas: ["Deogyang-gu", "Ilsandong-gu", "Ilsanseo-gu"],
      },
      {
        city: "Ansan",
        areas: ["Danwon-gu", "Sangnok-gu"],
      },
      { city: "Hwaseong", areas: [] },
      { city: "Namyangju", areas: [] },
      { city: "Pyeongtaek", areas: [] },
      { city: "Gimpo", areas: [] },
      { city: "Siheung", areas: [] },
      { city: "Uiwang", areas: [] },
      { city: "Hanam", areas: [] },
      { city: "Osan", areas: [] },
      { city: "Gwangmyeong", areas: [] },
      { city: "Icheon", areas: [] },
      { city: "Paju", areas: [] },
      { city: "Yangju", areas: [] },
      { city: "Gunpo", areas: [] },
      { city: "Dongducheon", areas: [] },
      { city: "Gwacheon", areas: [] },
      { city: "Gapyeong-gun", areas: [] },
      { city: "Yangpyeong-gun", areas: [] },
      { city: "Yeoju", areas: [] },
      { city: "Pocheon", areas: [] },
      { city: "Yeoncheon-gun", areas: [] },
    ],
  },
  {
    province: "Gangwon",
    type: "province",
    districts: [
      { city: "Chuncheon", areas: [] },
      { city: "Wonju", areas: [] },
      { city: "Gangneung", areas: [] },
      { city: "Donghae", areas: [] },
      { city: "Samcheok", areas: [] },
      { city: "Taebaek", areas: [] },
      { city: "Sokcho", areas: [] },
      { city: "Goseong-gun", areas: [] },
      { city: "Yanggu-gun", areas: [] },
      { city: "Hwacheon-gun", areas: [] },
      { city: "Pyeongchang-gun", areas: [] },
      { city: "Jeongseon-gun", areas: [] },
      { city: "Yeongwol-gun", areas: [] },
      { city: "Hongcheon-gun", areas: [] },
      { city: "Inje-gun", areas: [] },
    ],
  },
  {
    province: "Chungcheongbuk",
    type: "province",
    districts: [
      { city: "Cheongju", areas: ["Sangdang-gu", "Heungdeok-gu"] },
      { city: "Chungju", areas: [] },
      { city: "Jecheon", areas: [] },
      { city: "Boeun-gun", areas: [] },
      { city: "Okcheon-gun", areas: [] },
      { city: "Yeongdong-gun", areas: [] },
      { city: "Goesan-gun", areas: [] },
      { city: "Jeungpyeong-gun", areas: [] },
      { city: "Eumseong-gun", areas: [] },
      { city: "Danyang-gun", areas: [] },
    ],
  },
];
